### ISSUE TITLE
Failed to mount component: template or render function not defined.这是什么原因呢

### ISSUE THREAD

**Issue by shane-ryder** [forijk/vue-audio-better#12]
![image](https://user-images.githubusercontent.com/15341223/97548795-8d723780-1a0a-11eb-8621-41504937b0ab.png)
在 main.js添加了依赖
![image](https://user-images.githubusercontent.com/15341223/97548872-aa0e6f80-1a0a-11eb-9cc6-8c79529b118e.png)
求解？还缺少什么吗

**Comment by forijk** [comment]
再检查下您的其他部分代码吧，可能是由于某处 template 模板代码有误，或者 render function 有问题。
