### ISSUE TITLE
您好,想请问下,怎么监听  error /  ended  /  loadedmetadata 等一些原生的事件,求解答感谢

### ISSUE THREAD

**Issue by Artwinter** [forijk/vue-audio-better#25]
您好,想请问下,怎么监听  error /  ended  /  loadedmetadata 等一些原生的事件,求解答感谢

**Comment by forijk** [comment]
@Artwinter 实现方式不一样，不过可以做一些类似的事件监听

**Comment by Artwinter** [comment]
应该怎么做呢

**Comment by forijk** [comment]
@Artwinter 一种是 audio 标签，一种是 web audio api 标准，可以看下具体的文档哈~
