### ISSUE TITLE
请教 如何更改mini得背景色呢？

### ISSUE THREAD

**Issue by ufoozhenghao** [forijk/vue-audio-better#33]
大佬 打扰下，
我用的是Vue2，请教如何更改mini组件的背景颜色？

**Comment by Tsingkai** [comment]
> 大佬 打扰下， 我用的是Vue2，请教如何更改mini组件的背景颜色？

可以修改吗？

**Comment by ufoozhenghao** [comment]
> > 大佬 打扰下， 我用的是Vue2，请教如何更改mini组件的背景颜色？
> 
> 可以修改吗？

能改 很久远了 你好好找找

**Comment by Tsingkai** [comment]
> 

啥意思？我没看他有给方法改

**Comment by ufoozhenghao** [comment]
> > 
> 
> 啥意思？我没看他有给方法改

你直接在组件上设置背景颜色 可以覆盖掉默认的样式的 不行的话就加！important
