### ISSUE TITLE
请问没有事件绑定吗？

### ISSUE THREAD

**Issue by Sinboo** [forijk/vue-audio-better#4]
比方说onload 之类的。

**Comment by forijk** [comment]
感谢您的 issue~
这类的事件绑定暂时没加，后续我补充下吧，比如您说的 onload，或者获取音频相关信息等。

**Comment by forijk** [comment]
@Sinboo 感谢您的 issue~
这类的事件绑定暂时没加，后续我补充下吧，比如您说的 onload，或者获取音频相关信息等。
