### ISSUE TITLE
Using setSeek() method outside the component.

### ISSUE THREAD

**Issue by xXHeroooreHXx** [forijk/vue-audio-better#5]
I wanna use the method setSeek() in the component where I'm using VueAudio, how I have to call the method? I tried with VueAudio.setSeek(timeInSeconds) but i get that setSeek is not a function

**Comment by xXHeroooreHXx** [comment]
I was wrong, I only have to put a ref prop in the vue-audio component and call with this.$refs.refName.setSeek(timeInSeconds) thanks xD.

**Comment by forijk** [comment]
@xXHeroooreHXx 
Sorry, I did not reply in time.
Thank you for your issue. Yes, all methods can be called by obtaining the component instance through ref.
