### ISSUE TITLE
using the src attribute is dangerous, nuxt-lazy-load plugin is not letting it pass down!

### ISSUE THREAD

**Issue by deevannaveed** [forijk/vue-audio-better#7]
I cannot use this plugin with [nuxt-lazy-load](https://www.npmjs.com/package/nuxt-lazy-load/v/latest), the src attribute is not being passed down because nuxt-lazy-load is removing it to make i load lazy while it should not happen here, I think this attribute should have some different name.

**Comment by forijk** [comment]
@deevannaveed 
Thank you, you are right, I will change it later, or you can fork it first.

**Comment by deevannaveed** [comment]
@forijk I just opened a PR, it will be a breaking change so you may update the version number accordingly.

**Comment by forijk** [comment]
@deevannaveed  Thank you, the npm package has been republished ~

**Comment by deevannaveed** [comment]
> @deevannaveed  Thank you, the npm package has been republished ~

Thank you man, works great now!

**Comment by deevannaveed** [comment]
Fixed by changing the `src` prop `audio-source`.
